# Imports

In [2]:
from random import choice
from numpy import array, dot, random

import numpy as np


# AND Gate

In [3]:
step_function = lambda x: 0 if x < 100 else 1
# if input to function is < 100, do nothing, else fire 1
# why 100? 
# no reason, neuron will read data and learn weights that so with input



training_data = [
    (array([0,0 ,1]), 0),
    (array([0,1, 1]), 0),
    (array([1,0, 1]), 0),
    (array([1,1, 1]), 1),
]
# first two columns = x1 and x2 = input of gate
# third column = bias constant
# fourth column = y, output

w = random.rand(3)
print(w)
# random numbers for initialization of weight

errors = [] 
# array to capture errors made by neuron, aka, misfiring
# when should be 1 but neuron says 0
# errors = difference between what is expected and what is received

eta = 0.1
# will address later

n = 100000
# no of iterations
# how many times should neuron read data/learn relationship

for i in range(n):
    x, expected = choice(training_data)
    # choice = function to fandonly pick up one of the records
    # separate x and y columns
    # x = inner array in trainig data ex: array([0,0 ,1])


    result = dot(w, x)
    # weighted addition
    # linear summation: w1x1 + w2x2 + w3b3
    error = expected - step_function(result)
    # input summation to step function
    # step function checks whether input value is < 100, if so do nothing, else output 1
    errors.append(error)
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))


[0.22260755 0.58157063 0.1782617 ]
[0 0 1]: 33.27826169575134 -> 0
[0 1 1]: 66.95983232550174 -> 0
[1 0 1]: 66.60086924912267 -> 0
[1 1 1]: 100.28243987887306 -> 1


# OR Gate

In [6]:
step_function = lambda x: 0 if x < 100 else 1

training_data = [
    (array([0,0 ,1]), 0),
    (array([0,1, 1]), 1),
    (array([1,0, 1]), 1),
    (array([1,1, 1]), 1),
]
# everything remains the same except the data
# specifically, the outputs

w = random.rand(3)
print(w)

errors = [] 
eta = 0.1
n = 100000

for i in range(n):
    x, expected = choice(training_data)
    result = dot(w, x)
    error = expected - step_function(result)
    errors.append(error)
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))


[0.62282382 0.12897327 0.51633325]
[0 0 1]: 62.61633324553343 -> 0
[0 1 1]: 100.14530651356402 -> 1
[1 0 1]: 102.23915706609517 -> 1
[1 1 1]: 139.76813033412577 -> 1


# XNOR Gate

In [5]:
step_function = lambda x: 0 if x < 100 else 1

training_data = [
    (array([0,0 ,1]), 1),
    (array([0,1, 1]), 0),
    (array([1,0, 1]), 0),
    (array([1,1, 1]), 1),
]

w = random.rand(3)
print(w)

errors = [] 
eta = 0.1
n = 100000

for i in range(n):
    x, expected = choice(training_data)
    result = dot(w, x)
    error = expected - step_function(result)
    errors.append(error)
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))


[0.02788483 0.02236045 0.34119398]
[0 0 1]: 99.94119398097115 -> 0
[0 1 1]: 100.06355442698028 -> 1
[1 0 1]: 99.96907881342158 -> 0
[1 1 1]: 100.0914392594307 -> 1


In [4]:
# MCNeuron for And
w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]), 0),
    (array([1,0]), 0),
    (array([1,1]), 1),
]

step_function = lambda x: 0 if x < 2 else 1    # Step function with threshold of 2. Anything below is 0 

In [5]:
for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 0
[1 0]: 1.0 -> 0
[1 1]: 2.0 -> 1


In [6]:
# MCNeruon for OR
w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]), 1),
    (array([1,0]), 1),
    (array([1,1]), 1),
]

step_function = lambda x: 0 if x < 1 else 1    # Step function with threshold of 1. Anything below is 0 


In [7]:
for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 1


In [7]:
# MCNeuron for NAND

step_function = lambda x: 0 if x >= 2 else 1    # Step function with threshold of > 2 is 0 

w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 1),
    (array([0,1]), 1),
    (array([1,0]), 1),
    (array([1,1]), 0),
]

for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 1
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 0


In [20]:
# OR function in RB Neuron


step_function = lambda x: 0 if x < 100 else 1    # Step function with threshold of 0.5. Anything below is 0 


# AND gate
training_data = [
    (array([0,0 ,1]), 0),
    (array([0,1, 1]), 1),
    (array([1,0, 1]), 1),
    (array([1,1, 1]), 1),
]

w = random.rand(3)
b = .1    # initializing bias term
errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = choice(training_data)
    
   # w = np.append(w, b)

    result = dot(w, x)
    error = expected - step_function(result)   # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                       # that is the beauty of bias. The 'OR' pattern is learnt from data
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))


[0 0 1]: 62.61164356460525 -> 0
[0 1 1]: 100.0430120227679 -> 1
[1 0 1]: 101.11497157196007 -> 1
[1 1 1]: 138.5463400301227 -> 1
